title: National Population and Talent Division
url: "https://www.population.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /images/favicon-isomer.ico
colors:
  primary-color: '#83253B'
  secondary-color: '#6B1F31'
  media-colors:
    - title: media-color-one
      color: '#e98691'
    - title: media-color-two
      color: '#f30c0c'
    - title: media-color-three
      color: '#2b3033'
    - title: media-color-four
      color: '#2b3033'
    - title: media-color-five
      color: '#2b3033'
google_analytics: UA-31610992-1
resources_name: media-centre

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
future: true
description: test test

staging: https://pmo-population-staging.netlify.app,
prod: https://pmo-population-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
